version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.16
      environment:
        ## this enables colors in the output
        TERM: xterm
jobs:
  build:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
            - v4-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v4-deps-{{ .Branch }}-
            - v4-deps-
        - run:
            name: Install project dependencies
            command: | 
                yarn install
        - save_cache:
            key: v4-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - ~/.cache/yarn
        - persist_to_workspace:
            root: ~/
            paths:
            - .cache
            - project
            
  compile:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Build Source Files
            command: |
                yarn run build

  verify-test-publish:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Validate Swagger spec
            command: |
                yarn run swagger-validate-spec 
        - run:
            name: Run Pact Test & Generate Report
            command: |
                yarn run pact-test   
        - run:
            name: Validate Pact contract against Swagger spec
            command: |
                yarn run swagger-validate-pact     
        - run:
            name: Publish pacts
            command: |
                yarn run pact-publish 

  provider-verify:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/ 
        - run:
            name: Provider verification with pact
            command: |
                yarn run pact-verify-provider
workflows:
  version: 2
  build-compile-test-publish:
    jobs:
      - build
      - compile:
          requires:
            - build
      - verify-test-publish:
          context: pact-consumer-example-typescript
          requires:
            - compile
      - provider-verify:
          context: pact-consumer-example-typescript
          requires:
            - verify-test-publish
        