version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.14
      environment:
        ## this enables colors in the output
        TERM: xterm
jobs:
  build:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
        - run:
            name: Install project dependencies
            command: | 
                npm ci
        - save_cache:
            key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
            - ~/.npm
            - ~/.cache
        - persist_to_workspace:
            root: ~/
            paths:
            - .cache
            - project
            
  compile:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Build Source Files
            command: |
                npm run build

  test:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Run Pact Test & Generate Report
            command: |
                npm run pact-test

  publish:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Publish Pact Contract to Broker
            command: |
                npm run pact-publish
            

workflows:
  version: 2
  build-compile-test-publish:
    jobs:
      - build
      - compile:
          requires:
            - build
      - test:
          requires:
            - compile
      - publish:
          requires:
            - test